### ISSUE TITLE
Compatibility check for Chainer v2

### ISSUE THREAD

**Issue by milhidaka** [mil-tokyo/webdnn#271]
Currently, examples assumes Chainer v1.23.
Some incompatible changes seem to be applied to Chainer v2.

**Comment by milhidaka** [comment]
Function moved
```
Traceback (most recent call last):
  File "train_mnist_chainer.py", line 49, in <module>
    from webdnn.graph.converters.chainer import ChainerGraphConverter
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn-dev/src/graph_transpiler/webdnn/graph/converters/chainer.py", line 100, in <module>
    class LinearBlock(OperatorBlock):
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn-dev/src/graph_transpiler/webdnn/graph/converters/chainer.py", line 104, in LinearBlock
    def __init__(self, cfunc: chainer.functions.Linear):
AttributeError: module 'chainer.functions' has no attribute 'Linear'
```
