### ISSUE TITLE
Test fails due to circular import

### ISSUE THREAD

**Issue by milhidaka** [mil-tokyo/webdnn#394]
`nosetests` gives the following error:
```
======================================================================
ERROR: Failure: ImportError (cannot import name 'Operator')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hidaka/.pyenv/versions/3.6.0/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/hidaka/.pyenv/versions/3.6.0/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/hidaka/.pyenv/versions/3.6.0/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/hidaka/.pyenv/versions/3.6.0/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/hidaka/.pyenv/versions/3.6.0/lib/python3.6/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/hidaka/.pyenv/versions/3.6.0/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/test/webdnn_test/backend_test/webgpu_test/operators_test/col2im_test.py", line 3, in <module>
    from webdnn.backend.webgpu.operators.col2im import Col2Im
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/src/graph_transpiler/webdnn/backend/webgpu/operators/col2im.py", line 4, in <module>
    from webdnn.graph.operator import Operator
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/src/graph_transpiler/webdnn/graph/operator.py", line 3, in <module>
    from webdnn.graph import variable
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/src/graph_transpiler/webdnn/graph/variable.py", line 6, in <module>
    from webdnn.graph.operators import abs as operators_abs
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/src/graph_transpiler/webdnn/graph/operators/abs.py", line 1, in <module>
    from webdnn.graph.operators.elementwise import Elementwise
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/src/graph_transpiler/webdnn/graph/operators/elementwise.py", line 5, in <module>
    from webdnn.graph.operator import Operator
ImportError: cannot import name 'Operator'
```

**Comment by milhidaka** [comment]
Seems to be currently not occuring
