### ISSUE TITLE
subprocess.run can't call "type" shell-builtin command directry

### ISSUE THREAD

**Issue by knok** [mil-tokyo/webdnn#458]
On my environment, Debian 9, finding xcrun command by "type", it doesn't work.

```
Traceback (most recent call last):
  File "train_mnist_tensorflow.py", line 84, in <module>
    main()
  File "train_mnist_tensorflow.py", line 79, in main
    desc = generate_descriptor(backend, webdnn_graph)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/interface/generator.py", line 96, in generate_descriptor
    return generator(graph, **kwargs)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgpu/generator.py", line 115, in generate
    return WebGPUDescriptorGenerator.generate(graph, **kwargs)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgpu/generator.py", line 109, in generate
    validate_kernel_source(descriptor)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgpu/generator.py", line 54, in validate_kernel_source
    result = subprocess.run(["type", "xcrun"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/knok/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/knok/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/knok/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'type'
```

I modifyed the code calling shell explicitly, it works.

```
--- a/src/graph_transpiler/webdnn/backend/webgpu/generator.py
+++ b/src/graph_transpiler/webdnn/backend/webgpu/generator.py
@@ -51,7 +51,7 @@ def validate_kernel_source(descriptor: GraphDescriptor):
             f.write(source)
 
         with open(os.devnull, "w") as f:
-            result = subprocess.run(["type", "xcrun"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+            result = subprocess.run(["sh", "type", "xcrun"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
             if result.returncode != 0:
                 console.warning(
                     "[WebGPUDescriptorGenerator] 'xcrun' command is not found. validation of generated source code in webgpu backend is "
```

According to Wikipedia, "type" is not defined in POSIX, and it suggensts to use "command -V"
instead. I don't know which way is the best choice.

https://en.wikipedia.org/wiki/Type_(Unix)

**Comment by milhidaka** [comment]
Thanks for reporting. I changed the source to use 'command' instead of 'type'.

**Comment by knok** [comment]
I tried the latest code, but it still not work.
I tested on Ubuntu 16.

```
Traceback (most recent call last):
  File "train_mnist_tensorflow.py", line 84, in <module>
    main()
  File "train_mnist_tensorflow.py", line 79, in main
    desc = generate_descriptor(backend, webdnn_graph)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/interface/generator.py", line 96, in generate_descriptor
    return generator(graph, **kwargs)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgpu/generator.py", line 122, in generate
    return WebGPUDescriptorGenerator.generate(graph, **kwargs)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgpu/generator.py", line 116, in generate
    validate_kernel_source(descriptor)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/webgpu/generator.py", line 61, in validate_kernel_source
    result = subprocess.run(["command", "-V", "xcrun"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/knok/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/knok/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/knok/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'command'
```

It must be calling "sh" explicitly.

```
--- a/src/graph_transpiler/webdnn/backend/webgpu/generator.py
+++ b/src/graph_transpiler/webdnn/backend/webgpu/generator.py
@@ -58,7 +58,7 @@ def validate_kernel_source(descriptor: GraphDescriptor):
             f.write(source)
 
         with open(os.devnull, "w") as f:
-            result = subprocess.run(["command", "-V", "xcrun"], stdout=subproce
ss.PIPE, stderr=subprocess.PIPE)
+            result = subprocess.run(["sh", "command", "-V", "xcrun"], stdout=su
bprocess.PIPE, stderr=subprocess.PIPE)
             if result.returncode != 0:
                 console.warning(
                     "[WebGPUDescriptorGenerator] 'xcrun' command is not found. 
validation of generated source code in webgpu backend is "
```

**Comment by milhidaka** [comment]
`sh command -V xcrun` is ok at mac, but gives
```
sh: 0: Can't open command
```
on Ubuntu.

Instead, I changed to catch the FileNotFoundError on running xcrun.

**Comment by knok** [comment]
commit 3af61ea28908a0d7f7132e4a3c8153569b082831 works fine on my environment.
Thank you!
