### ISSUE TITLE
Exponential time increase  in Chainer model conversion

### ISSUE THREAD

**Issue by Aixile** [mil-tokyo/webdnn#478]
Sample Code:
https://gist.github.com/Aixile/0cf934344271c8d132378cea87bd73f2
Need about 100 seconds to convert this model with master version (macOS Sierra and Chainer 2.0.2)
It is caused by some mistakes in stack operation. https://github.com/mil-tokyo/webdnn/blob/master/src/graph_transpiler/webdnn/frontend/chainer/converter.py#L55-L73

BTW, 
Current version lost compatibility with Chainer 1.x, running the above script with Chainer 1.24.0 will give the following error.
```
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    graph = ChainerConverter().convert([x], [y])
  File "/Users/aixile/anaconda3/envs/snakes/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/chainer/converter.py", line 158, in convert
    self._convert_var(c_var, constant=(c_var not in inputs))
  File "/Users/aixile/anaconda3/envs/snakes/lib/python3.6/site-packages/chainer/variable.py", line 512, in __eq__
    raise NotImplementedError()
NotImplementedError
```

**Comment by Kiikurage** [comment]
Thank you for your report. we'll fix it soon.

**Comment by Kiikurage** [comment]
OK, all bugs are fixed.

**Comment by Aixile** [comment]
Succeed! Thanks!
