### ISSUE TITLE
Not work mnist chainer example using GPU

### ISSUE THREAD

**Issue by knok** [mil-tokyo/webdnn#488]
I tried to run mnist example with chainer and using gpu, but it causes the following error:

```
Traceback (most recent call last):
  File "train_mnist_chainer.py", line 212, in <module>
    main()
  File "train_mnist_chainer.py", line 196, in main
    y = model.predictor(x)
  File "train_mnist_chainer.py", line 70, in __call__
    h1 = F.hard_sigmoid(self.l1(x))
  File "/opt/p36/lib/python3.6/site-packages/chainer/links/connection/linear.py", line 127, in __call__
    return linear.linear(x, self.W, self.b)
  File "/opt/p36/lib/python3.6/site-packages/chainer/functions/connection/linear.py", line 107, in linear
    return LinearFunction()(x, W, b)
  File "/opt/p36/lib/python3.6/site-packages/chainer/function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "/opt/p36/lib/python3.6/site-packages/chainer/functions/connection/linear.py", line 40, in forward
    .format(type(W), type(x)))
ValueError: numpy and cupy must not be used together
type(W): <class 'cupy.core.core.ndarray'>, type(x): <class 'numpy.ndarray'>
```
Patch:

```
--- a/example/mnist/train_mnist_chainer.py
+++ b/example/mnist/train_mnist_chainer.py
@@ -190,6 +190,8 @@ def main():
 
     print('Transpiling model to WebDNN graph descriptor')
 
+    if args.gpu >= 0:
+        model.to_cpu()
     example_input = numpy.expand_dims(train[0][0], axis=0)  # example input (an
ything ok, (batch_size, 784))
     x = chainer.Variable(example_input)
     # y = F.softmax(model.predictor(x))  # run model
```

**Comment by milhidaka** [comment]
Thanks for suggestion of bug fix.
I confirmed it works and merged in #502.
