### ISSUE TITLE
Not work minst chainer example using "conv" model

### ISSUE THREAD

**Issue by knok** [mil-tokyo/webdnn#489]
```
 % python train_mnist_chainer.py --model conv -g 0    
GPU: 0
# Minibatch-size: 100
# epoch: 5

epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           0.511279    0.297088              0.856134       0.9163                    33.7006
2           0.303343    0.274152              0.912901       0.9201                    66.1639
3           0.281337    0.25734               0.918951       0.9279                    98.6847
4           0.238706    0.205019              0.931668       0.9405                    131.292
5           0.178062    0.145548              0.948334       0.9569                    163.862
Transpiling model to WebDNN graph descriptor
Traceback (most recent call last):
  File "train_mnist_chainer.py", line 214, in <module>
    main()
  File "train_mnist_chainer.py", line 199, in main
    graph = ChainerConverter().convert([x], [y])  # convert graph to intermediate representation
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/chainer/converter.py", line 168, in convert
    self._convert_operator(c_opr)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/converter.py", line 108, in _convert_operator
    self._handler_map[self.__class__.__name__][operator_key](self, operator)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/chainer/functions/connection.py", line 138, in _convert_linear_function
    y, = Linear(None)(x2, w2)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/graph/operators/linear.py", line 48, in __call__
    assert x.shape_dict[Axis.C] == w.shape_dict[Axis.C], "Input and Weight variable of Linear operator must have same shape " \
AssertionError: Input and Weight variable of Linear operator must have same shape except Axis.N size: x.shape_dict[Axis.C]=123904, size: w.shape_dict[Axis.C]=7744
```

It seems the last linear layer's shapes of  weights and input unmatched.
I'm not sure how to fix it...

**Comment by Kiikurage** [comment]
Thank you for your report. Same issue can be reproduced. I'll fix it.

**Comment by Kiikurage** [comment]
Ok, the bug is fixed. please check it.

**Comment by knok** [comment]
It works fine on me. Thank you.
