### ISSUE TITLE
convert_caffe.py: convert() takes 3 positional

### ISSUE THREAD

**Issue by kylemcdonald** [mil-tokyo/webdnn#574]
Testing on the latest version of webdnn on Ubuntu 16.04 and Python 3.6. Running the `caffenet_conversion.ipynb`, on this line: `!python ../../bin/convert_caffe.py --input_name data --input_shape '(1,3,227,227)' --output_names fc8 --out output data/bvlc_reference_caffenet.caffemodel` there is an error:

```
[convert_caffe] Loading caffe model... (usually takes several minutes)
[convert_caffe] Generating feedforward graph
Traceback (most recent call last):
  File "../../bin/convert_caffe.py", line 103, in <module>
    main()
  File "../../bin/convert_caffe.py", line 75, in main
    graph = converter.convert(chainer_cg, [input_blob], output_blobs)  # type: Graph
TypeError: convert() takes 3 positional arguments but 4 were given
```

It looks like line 75:

```
graph = converter.convert(chainer_cg, [input_blob], output_blobs)
```

Should probably read:

```
graph = converter.convert([input_blob], output_blobs)
```

But I'm not sure. When I switch the code, and run from the command line (to make sure that the environment variables are all set correctly) then I get:

```
$ python ../../bin/convert_caffe.py --input_name data --input_shape '(1,3,227,227)' --output_names fc8 --out output data/bvlc_reference_caffenet.caffemodel
[convert_caffe] Loading caffe model... (usually takes several minutes)
[convert_caffe] Generating feedforward graph
[convert_caffe] Generating descriptors
/home/kyle/anaconda3/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/util/console.py:27: Warning: [WebGPUDescriptorGenerator] 'xcrun' command is not found. validation of generated source code in webgpu backend is skipped.
  warnings.warn(message, category)
INFO:root:generating system library: libcxxabi.bc... (this will be cached in "/home/kyle/.emscripten_cache/asmjs/libcxxabi.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: dlmalloc.bc... (this will be cached in "/home/kyle/.emscripten_cache/asmjs/dlmalloc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc.bc... (this will be cached in "/home/kyle/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: wasm-libc.bc... (this will be cached in "/home/kyle/.emscripten_cache/asmjs/wasm-libc.bc" for subsequent builds)
INFO:root: - ok
```

Which looks good to me. Next I need to try it on a model that is smaller so I can actually test it :)

**Comment by Kiikurage** [comment]
Thanks for your report. It's out-of-dated interface and i've updated it (#575). Please retry with the latest revision.

**Comment by kylemcdonald** [comment]
Thanks! I can confirm the change works 🙏
