### ISSUE TITLE
TypeError: object of type 'TensorVariable' has no len()

### ISSUE THREAD

**Issue by lagleki** [mil-tokyo/webdnn#583]
$ `python ./bin/convert_keras.py resnet50.h5 --input_shape '(1,224,224,3)' --out output`

```
Using Theano backend.
[convert_keras.py] Generating feedforward graph
Traceback (most recent call last):
  File "./bin/convert_keras.py", line 113, in <module>
    main()
  File "./bin/convert_keras.py", line 63, in main
    graph = converter.convert(model)
  File "/home/user/miniconda3/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/keras/converter.py", line 104, in convert
    self._convert_tensors(model.inputs, input_orders)
  File "/home/user/miniconda3/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/keras/converter.py", line 148, in _convert_tensors
    for tf_tensor, order in zip(tf_tensors, orders)]
  File "/home/user/miniconda3/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/keras/converter.py", line 148, in <listcomp>
    for tf_tensor, order in zip(tf_tensors, orders)]
  File "/home/user/miniconda3/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/keras/converter.py", line 34, in get_default_order
    if len(tf_tensor.shape) == 2:
TypeError: object of type 'TensorVariable' has no len()
```

**Comment by Kiikurage** [comment]
Sorry, currently only TensorFlow backend is supported.
