### ISSUE TITLE
CaffeFunction does not support HDF5Data layer

### ISSUE THREAD

**Issue by zcregan** [mil-tokyo/webdnn#628]
I'm trying to run this project in the browser: https://github.com/kpzhang93/MTCNN_face_detection_alignment

So I started by trying to convert the first model here:
https://github.com/kpzhang93/MTCNN_face_detection_alignment/tree/master/code/codes/MTCNNv1/model

Using the following command:
```
python ../../bin/convert_caffe.py --input_name data --input_shape '(1,3,12,12)' --output_names prob1 --out output ../../../MTCNN_face_detection_alignment/code/codes/MTCNNv1/model/det1.caffemodel
```

But it's returning this error:
```
[convert_caffe] Loading caffe model... (usually takes several minutes)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py:153: UserWarning: Skip the layer "data12", since CaffeFunction does notsupport HDF5Data layer
  'support %s layer' % (layer.name, layer.type))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py:153: UserWarning: Skip the layer "silence", since CaffeFunction does notsupport Silence layer
  'support %s layer' % (layer.name, layer.type))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py:153: UserWarning: Skip the layer "PReLU1", since CaffeFunction does notsupport PReLU layer
  'support %s layer' % (layer.name, layer.type))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py:153: UserWarning: Skip the layer "PReLU2", since CaffeFunction does notsupport PReLU layer
  'support %s layer' % (layer.name, layer.type))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py:153: UserWarning: Skip the layer "PReLU3", since CaffeFunction does notsupport PReLU layer
  'support %s layer' % (layer.name, layer.type))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py:153: UserWarning: Skip the layer "loss2", since CaffeFunction does notsupport EuclideanLoss layer
  'support %s layer' % (layer.name, layer.type))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py:153: UserWarning: Skip the layer "accuracy1", since CaffeFunction does notsupport Accuracy layer
  'support %s layer' % (layer.name, layer.type))
[convert_caffe] Generating feedforward graph
Traceback (most recent call last):
  File "../../bin/convert_caffe.py", line 102, in <module>
    main()
  File "../../bin/convert_caffe.py", line 69, in main
    link(inputs={args.input_name: input_blob}, outputs=output_names))  # list of Variable
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py", line 215, in __call__
    return tuple(variables[blob] for blob in outputs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py", line 215, in <genexpr>
    return tuple(variables[blob] for blob in outputs)
KeyError: 'prob1'
```
Do all of those unsupported layers mean these models just aren't going to be possible to convert?

**Comment by milhidaka** [comment]
WebDNN loads Caffe model using Chainer's feature of converting the model for Chainer.
https://docs.chainer.org/en/stable/reference/caffe.html

Your error is that Chainer does not support conversion of some layers.
To solve the problem, you need to modify Chainer, not WebDNN.
It seems that at least PReLU layer have to be converted. In contrast, Accuracy layer may be left unsupported because it is not on the path of obtaining `prob1`.
