### ISSUE TITLE
Cause an error when generate computation graph using caffe model

### ISSUE THREAD

**Issue by dhgrs** [mil-tokyo/webdnn#701]
Hi, I tried to generate computation graph using caffe model via chainer. But I got an error that `AttributeError: 'NoneType' object has no attribute 'data'`.

I use chainer==3.1.0 and webdnn==1.1.0. Here is the code.
```
import argparse
from enum import Enum
from os import path

import chainer
from chainer.links import caffe

from webdnn.backend import generate_descriptor
from webdnn.frontend.chainer import ChainerConverter, PlaceholderVariable
from webdnn.graph.placeholder import Placeholder


parser = argparse.ArgumentParser()
parser.add_argument("--backend", default="webgpu",
                    choices=["webgpu", "webgl", "webassembly", "fallback"])
parser.add_argument("--encoding")
args = parser.parse_args()

print(f"backend: {args.backend}")
print(f"encoding: {args.encoding}")

# Load chainer pre-trained model
model_path = 'nsfw_model/resnet_50_1by2_nsfw.caffemodel'
if not path.exists(model_path):
    raise FileNotFoundError(f"Model data is not found. Please download from " +
                            "'https://github.com/yahoo/open_nsfw'")
model = caffe.CaffeFunction(model_path)

# Execute forward propagation to construct computation graph

# By using "Placeholder" object,
# actual input image size can be determined at runtime.
H = Placeholder(label="H")
W = Placeholder(label="W")

# You can use the "PlaceholderVariable" instance like "chainer.Variable".
x = PlaceholderVariable([1, 3, 224, 224])

with chainer.using_config("train", False):  # fixes batch normalization
    y, = model(inputs={'data': x}, outputs=['eltwise_stage3_block2'],
               disable=['pool', 'fc_nsfw', 'prob'])

W = model.fc_nsfw.W.data.reshape(2, 1024, 1, 1)
b = model.fc_nsfw.b.data
output = chainer.functions.softmax(
    chainer.functions.convolution_2d(y, W, b))
score = output[0, :1]
# score = chainer.functions.resize_images(output, (H, W))[0, :1]
# score *= x

# Convert chainer computation graph into IR
graph = ChainerConverter().convert([x], [score])

# Generate graph descriptor
generate_descriptor(
    args.backend, graph,
    constant_encoder_name=args.encoding).save(path.join(path.dirname(__file__),
                                                        "./output"))
```

**Comment by Kiikurage** [comment]
Please give us the complete error message

**Comment by dhgrs** [comment]
This is the log.
```
backend: webassembly
encoding: None
/home/user/miniconda3/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py:118: UserWarning: Skip the layer "data", since CaffeFunction does notsupport MemoryData layer
  'support %s layer' % (layer.name, layer.type))
Traceback (most recent call last):
  File "convert.py", line 52, in <module>
    graph = ChainerConverter().convert([x], [score])
  File "/home/user/miniconda3/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/chainer/converter.py", line 223, in convert
    self._convert_var(node, constant=node not in input_set)
  File "/home/user/miniconda3/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/chainer/converter.py", line 246, in _convert_var
    data = get_variable_data(c_var)
  File "/home/user/miniconda3/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/frontend/chainer/converter.py", line 56, in get_variable_data
    return variable._variable().data if variable.data is None else variable.data
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by Kiikurage** [comment]
I understand why the error occurred.

```python
W = model.fc_nsfw.W.data.reshape(2, 1024, 1, 1)
b = model.fc_nsfw.b.data
output = chainer.functions.softmax(chainer.functions.convolution_2d(y, W, b))
```

Here, `W` and `b` are originally `np.array` instance and `Variable` instances are created in `chainer.functions.Convolution2D` instance. However, these `Variable` instance is not referenced from any variable and will be automatically released after forward propagation finished. Therefore WebDNN cannot traversed computation graph.

To solve this problem, the code must be changed like follows:

```py
# instantiate Variable by yourself and keep references
W = chainer.Variable(model.fc_nsfw.W.data.reshape(2, 1024, 1, 1))
b = chainer.Variable(model.fc_nsfw.b.data)
output = chainer.functions.softmax(chainer.functions.convolution_2d(y, W, b))
```

For same reason, you also need to change

```py
# BEFORE
with chainer.using_config("train", False):  # fixes batch normalization
    y, = model(inputs={'data': x}, outputs=['eltwise_stage3_block2'], disable=['pool', 'fc_nsfw', 'prob'])
```

to

```py
# AFTER
with chainer.using_config("train", False):  # fixes batch normalization
     y, = model(inputs={'data': x}, outputs=['eltwise_stage3_block2'], disable=['pool', 'fc_nsfw', 'prob'])

     import chainer.computational_graph
     for node in chainer.computational_graph.build_computational_graph([y]).nodes:
         if "BatchNormalization" in type(node).__name__:
            # instantiate Variable of "gamma" and "beta" by yourself and keep references in "node.gamma", "node.beta"
             node.gamma = chainer.Variable(np.ones(node.inputs[0].shape[1]))
             node.beta = chainer.Variable(np.zeros(node.inputs[0].shape[1]))
             node.inputs = (node.inputs[0], node.gamma.node, node.beta.node, *node.inputs[3:])
```

Note that this solution is just *dirty-hack*.

**Comment by dhgrs** [comment]
Thanks for reply! I tried wrapping W and b in variable before this issue but didn't notice the parameters of batch normalization. I hope that WebDNN will support this case easily!

**Comment by Kiikurage** [comment]
FYI: WebDNN's `Placeholder` cannot used as Chainer's hyper parameters such as output size of `F.resize_image`.

One work around is separating computation graph by 2 parts.

```python
output = chainer.functions.softmax(chainer.functions.convolution_2d(y, kernel, b))

# NG: WebDNN's placeholder cannot be used as Chainer's hyperparameters
# score = chainer.functions.resize_images(output, (H, W))[0, :1]  # ERROR!

# OK: Build 2 computation graphs
graph1 = ChainerConverter().convert([x], [output])

resized_output = chainer.Variable(np.zeros(1, 1, x.shape[2], x.shape[3]))  # pseudo input for resized score.
score = resized_output * x
graph2 = ChainerConverter().convert([x, resized_output], [score])
```

and implementing resizing operation in JS:

```js
// JavaScript
let runner1 = await WebDNN.load(model1_path);
let runner2 = await WebDNN.load(model2_path);

let x1 = runner1.getInputViews()[0];
let output = runner1.getOutputViews()[0];

let x2 = runner2.getInputViews()[0];
let resized_output = runner2.getInputViews()[1];
let score = runner2.getOutputViews()[0];

/**
 * 1. Run graph1
 */
x1.set(await WebDNN.Image.getImageArray(input_image_canvas));
await runner1.run();

/**
 * 2. Resize output:  (outH, outW) -> (resizedH, resizedW)
 */
let dummy_canvas = document.createElement('canvas');
dummy_canvas.height = resizedH;
dummy_canvas.width = resizedW;

// @see https://mil-tokyo.github.io/webdnn/docs/api_reference/descriptor-runner/modules/webdnn_image.html#getimagearray
WebDNN.Image.setImageToCanvas(output.toActual(), outH, outW, {
  color: WebDNN.Image.Color.GREY,
  srcH: outH,  srcW: outW,
  dstH: resizedH, dstW: resizedW,
});

/**
 * 3. Run graph2
 */
x2.set(await WebDNN.Image.getImageArray(input_image_canvas));
resized_output.set(await WebDNN.Image.getImageArray(dummy_canvas, {
  color: WebDNN.Image.Color.GREY
});
await runner2.run();
```
