### ISSUE TITLE
Operator "ConvTranspose" is not supported yet

### ISSUE THREAD

**Issue by nerox8664** [mil-tokyo/webdnn#782]
Hello! I've a problem with convertation my model to the webdnn format:

```
Traceback (most recent call last):
  File "convert_to_dnn.py", line 31, in <module>
    graph = PyTorchConverter().convert(model, dummy_input)
  File "/usr/lib/python3.6/site-packages/webdnn/frontend/pytorch/converter.py", line 92, in convert
    graph = ONNXConverter().convert(onnx.load(proto_path))
  File "/usr/lib/python3.6/site-packages/webdnn/frontend/onnx/converter.py", line 94, in convert
    self._convert_operator(onnx_op)
  File "/usr/lib/python3.6/site-packages/webdnn/frontend/onnx/converter.py", line 114, in _convert_operator
    super(ONNXConverter, self)._convert_operator(proto)
  File "/usr/lib/python3.6/site-packages/webdnn/frontend/converter.py", line 117, in _convert_operator
    self._handler_map[self.__class__.__name__][operator_key](self, operator)
  File "/usr/lib/python3.6/site-packages/webdnn/frontend/onnx/defs/nn.py", line 108, in _convert_conv_transpose
    raise NotImplementedError("[ONNXConverter] Operator \"ConvTranspose\" is not supported yet.")
NotImplementedError: [ONNXConverter] Operator "ConvTranspose" is not supported yet.
```

So, will you add the ConvTranspose in future?

**Comment by milhidaka** [comment]
WebDNN has been completely rewritten as **v2.0.0-alpha**, a browser-based ONNX inference runtime. The v1 converter that produced this error no longer exists, so the original issue is no longer actionable.

For reference, this operator is now implemented in the v2 ONNX runtime.

Closing as *not planned*. Thanks for the report!
