### ISSUE TITLE
NotImplementedError: [KerasConverter] keras.layers.UpSampling2D is not supported

### ISSUE THREAD

**Issue by gmalivenko** [mil-tokyo/webdnn#784]
Hello! There is a one more issue with converter:

```
Traceback (most recent call last):
  File "convert_keras.py", line 114, in <module>
    main()
  File "convert_keras.py", line 64, in main
    graph = converter.convert(model)
  File "/home/nero/webdnn/src/graph_transpiler/webdnn/frontend/keras/converter.py", line 115, in convert
    return self._convert_fallback(model)
  File "/home/nero/webdnn/src/graph_transpiler/webdnn/frontend/keras/converter.py", line 129, in _convert_fallback
    self._convert_operator(node.outbound_layer)
  File "/home/nero/webdnn/src/graph_transpiler/webdnn/frontend/keras/converter.py", line 162, in _convert_operator
    return super(KerasConverter, self)._convert_operator(k_op)
  File "/home/nero/webdnn/src/graph_transpiler/webdnn/frontend/converter.py", line 117, in _convert_operator
    self._handler_map[self.__class__.__name__][operator_key](self, operator)
  File "/home/nero/webdnn/src/graph_transpiler/webdnn/frontend/keras/layers/convolutional.py", line 207, in _convert_up_sampling2d
    raise NotImplementedError('[KerasConverter] keras.layers.UpSampling2D is not supported')
NotImplementedError: [KerasConverter] keras.layers.UpSampling2D is not supported
```

will you add the UpSampling2D in future?

**Comment by milhidaka** [comment]
WebDNN has been completely rewritten as **v2.0.0-alpha**, a browser-based ONNX inference runtime (load an ONNX model directly in the browser; no Python conversion step). The v1 Keras / Chainer / TensorFlow / Caffe converters and the old backends that this issue refers to no longer exist, so this report is no longer actionable against the current codebase.

Closing as *not planned*. Thanks for the report!
