### ISSUE TITLE
Placeholder on KerasConverter fails

### ISSUE THREAD

**Issue by milhidaka** [mil-tokyo/webdnn#799]
https://github.com/mil-tokyo/webdnn/blob/0404965e6ac872e0c7c5b123227a56b921dd7ccb/src/graph_transpiler/webdnn/frontend/keras/converter.py#L55
Says "None" will be placeholder, but it causes exception.

```
Traceback (most recent call last):
  File "train_mnist_keras.py", line 204, in <module>
    main()
  File "train_mnist_keras.py", line 196, in main
    model, graph = generate_graph(args.model, args.out)
  File "train_mnist_keras.py", line 185, in generate_graph
    graph = KerasConverter(batch_size=None).convert(model)  # None to indicate batch_size will be placeholder label "N"
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/src/graph_transpiler/webdnn/frontend/keras/converter.py", line 115, in convert
    return self._convert_fallback(model)
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/src/graph_transpiler/webdnn/frontend/keras/converter.py", line 125, in _convert_fallback
    v.shape[0].value = self._batch_size
  File "/Users/hidaka/miljs/mil-web-dnn/webdnn/src/graph_transpiler/webdnn/graph/placeholder.py", line 508, in value
    raise TypeError(f"Placeholder#value must be a int, not '{type(new_v)}'")
TypeError: Placeholder#value must be a int, not '<class 'NoneType'>'
```

**Comment by milhidaka** [comment]
WebDNN has been completely rewritten as **v2.0.0-alpha**, a browser-based ONNX inference runtime (load an ONNX model directly in the browser; no Python conversion step). The v1 Keras / Chainer / TensorFlow / Caffe converters and the old backends that this issue refers to no longer exist, so this report is no longer actionable against the current codebase.

Closing as *not planned*. Thanks for the report!
