### ISSUE TITLE
cannot convert batch normalization of TensorFlow model.

### ISSUE THREAD

**Issue by y-ich** [mil-tokyo/webdnn#824]
Hi.

I am trying to convert a TensorFlow model for WebDNN and encountered the following error.
(convert_webdnn.py is my script.)

    Traceback (most recent call last):
      File "convert_webdnn.py", line 36, in <module>
        graph = TensorFlowConverter(tfprocess.session).convert(x[0:1], [tfprocess.y_conv, tfprocess.z_conv])
      File "/Users/yuji/.virtualenvs/py3webdnn/lib/python3.6/site-packages/webdnn-1.2.3-py3.6.egg/webdnn/frontend/tensorflow/converter.py", line 97, in convert
        self._convert_operator(op)
      File "/Users/yuji/.virtualenvs/py3webdnn/lib/python3.6/site-packages/webdnn-1.2.3-py3.6.egg/webdnn/frontend/converter.py", line 117, in _convert_operator
        self._handler_map[self.__class__.__name__][operator_key](self, operator)
      File "/Users/yuji/.virtualenvs/py3webdnn/lib/python3.6/site-packages/webdnn-1.2.3-py3.6.egg/webdnn/frontend/tensorflow/ops/gen_control_flow_ops.py", line 83, in switch_handler
        f"[TensorFlowConverter] 'Switch' operator with dynamic condition is not supported.")
    AssertionError: [TensorFlowConverter] 'Switch' operator with dynamic condition is not supported.

And I found that tf.layers.batch_normalization uses Switch though I am not sure about dynamic condition.
Are there any ways to avoid this error?

Thank you.

**Comment by milhidaka** [comment]
It seems that "Switch" is used to change computational graph on training and testing.
If you are sure the value of the condition value on testing, a workaround is remove the assert and fix the if statement to True or False.
https://github.com/mil-tokyo/webdnn/blob/5e1062f2ad1eebf97a0f050d0d18e41a179a1193/src/graph_transpiler/webdnn/frontend/tensorflow/ops/gen_control_flow_ops.py#L86

**Comment by milhidaka** [comment]
When constructing model, setting `tf.layers.batch_normalization(training=False)` instead of using placeholder to training argument may avoid the issue.
The flow is:

1. Train the model with `training=True` and save model weights
2. Modify the code to `training=False`
3. Run the program and construct model and load trained weight, then supply it to webdnn

**Comment by y-ich** [comment]
I succeeded to convert my model according to your advice!
Thank you!
