### ISSUE TITLE
tensorflow example failure

### ISSUE THREAD

**Issue by DavidGOrtega** [mil-tokyo/webdnn#862]
Hi, 

Im trying to convert a Tensorflow pb file for testing purposes. The model is inception_v3_2016_08_28_frozen.pb that can be found here:

https://www.tensorflow.org/tutorials/image_recognition

However Im having the problem of having all the shapes unknown.

```
 model_path  = 'inception_v3_2016_08_28_frozen.pb'
    out_path    = './../models/inception_v3_2016_08_28_frozen'
    
    with tf.gfile.GFile(model_path, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
 
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def,
          input_map=None,
          return_elements=None,
          name="")

    tfsession   = tf.Session(graph=graph)
    
    
    
    in_1        = tfsession.graph.get_tensor_by_name("input:0")
    out_1       = tfsession.graph.get_tensor_by_name("output:0")
  
    print( tfsession.graph.get_operation_by_name("input") )
    print( tfsession.graph.get_operation_by_name("output") )
    print( [in_1, out_1])
    
    graph       = TensorFlowConverter(tfsession).convert([in_1], [out_1])
    
    exec_info   = generate_descriptor("webgpu", graph)  # also "webassembly", "webgl", "fallback" are available.
    exec_info.save(out_path)
```

the error is:

```
[<tf.Tensor 'input:0' shape=<unknown> dtype=float32>, <tf.Tensor 'output:0' shape=<unknown> dtype=uint8>]
Traceback (most recent call last):
  File "tftest.py", line 60, in <module>
    convert_graph(model_path, out_path)
  File "tftest.py", line 47, in convert_graph
    graph       = TensorFlowConverter(tfsession).convert([in_1], [out_1])
  File "/usr/local/lib/python3.6/site-packages/webdnn-1.2.5-py3.6.egg/webdnn/frontend/tensorflow/converter.py", line 89, in convert
    shape = [Placeholder() if dim.value is None else dim.value for dim in tensor.shape.dims]
TypeError: 'NoneType' object is not iterable
```

I had Tensorflow 1.8 but I downgraded it to 1.4. to use webdnn

I have seen the QuantizationV2 is not supported either 😟 

As fas I as I can see is a matter of the unknown shapes...

**Comment by DavidGOrtega** [comment]
My bad, the error is not that, thats the error in the quantized model
