### ISSUE TITLE
SqueezeNet num_classes=1 no WebGL

### ISSUE THREAD

**Issue by desrius** [mil-tokyo/webdnn#886]
When I try to convert my SqueezeNet Keras Model with one output Class I get this assertion error for webgl:

```
[convert_keras.py] Failed generating descriptor for webgl backend
Traceback (most recent call last):
  File "bin/convert_keras.py", line 97, in main
    graph_exec_data = generate_descriptor(backend, graph, constant_encoder_name=args.encoding)
  File "/home/*/anaconda3/lib/python3.6/site-packages/webdnn-1.2.6-py3.6.egg/webdnn/backend/interface/generator.py", line 107, in generate_descriptor
    return generator(graph, **kwargs)
  File "/home/*/anaconda3/lib/python3.6/site-packages/webdnn-1.2.6-py3.6.egg/webdnn/backend/webgl/generator.py", line 92, in generate
    return WebGLDescriptorGenerator.generate(graph, **kwargs)
  File "/home/*/anaconda3/lib/python3.6/site-packages/webdnn-1.2.6-py3.6.egg/webdnn/backend/webgl/generator.py", line 61, in generate
    kernels = cls.generate_kernels(graph)
  File "/home/*/anaconda3/lib/python3.6/site-packages/webdnn-1.2.6-py3.6.egg/webdnn/backend/webgl/generator.py", line 86, in generate_kernels
    kernels += cls._handler_map[cls.__name__][key](op)
  File "/home/*/anaconda3/lib/python3.6/site-packages/webdnn-1.2.6-py3.6.egg/webdnn/backend/webgl/kernels/reshape.py", line 77, in reshape
    convert_position("gl_FragCoord.yx", texture_shape(y)[:2], texture_stride(y)[:2], shapes_y_dy[y], strides_y_dy[y]),
  File "/home/*/anaconda3/lib/python3.6/site-packages/webdnn-1.2.6-py3.6.egg/webdnn/backend/webgl/kernels/util.py", line 53, in convert_position
    ivec(out_stride), ", ",
  File "/home/*/anaconda3/lib/python3.6/site-packages/webdnn-1.2.6-py3.6.egg/webdnn/backend/webgl/kernels/util.py", line 100, in ivec
    assert 2 <= len(sequence) <= 4
AssertionError
```
When I increase the number of classes to 2, it works. I use pytorch2keras to convert the squeezenet model from pytorch to keras.

**Comment by milhidaka** [comment]
WebDNN has been completely rewritten as **v2.0.0-alpha**, a browser-based ONNX inference runtime (load an ONNX model directly in the browser; no Python conversion step). The v1 Keras / Chainer / TensorFlow / Caffe converters and the old backends that this issue refers to no longer exist, so this report is no longer actionable against the current codebase.

Closing as *not planned*. Thanks for the report!
