### ISSUE TITLE
Does this run at all on Edge?

### ISSUE THREAD

**Issue by jeffsaremi** [mil-tokyo/webdnn#905]
"webdnn": "^1.2.6"

I get the following when I try to run the Resnet50 example:

```
        Edge 18.18242.0 (Windows 10.0.0)
      RangeError: Invalid offset/length when creating typed array
         at prototype.syncWriteViews (dist/main.js:38:109090)
         at Generator.prototype.next (native code)
         at p.prototype.run (dist/main.js:38:105551)
         at Generator.prototype.next (native code)
         at Yi.prototype.runModel (dist/main.js:111:240771)
         at Generator.prototype.next (native code)
         at Hi (dist/main.js:111:238000)
         at Generator.prototype.next (native code)
```

Here's the relevant pieces of the code that I use to run this model:

```
        this.model = await WebDNN.load(modelPath, {backendOrder: backend});
        const data= WebDNN.Image.getImageArrayFromImageData(
            {data:data, width:this.imageSize, height:this.imageSize}, options);
        console.log(`input size: ${data.length}`);
        this.model.inputs[0].set(data);
        await this.model.run();
        const outputData = this.model.outputs[0];
```

**Comment by milhidaka** [comment]
Thank you for reporting.
I reproduced the problem with webgl backend, chainer frontend.
I will investigate the problem.

**Comment by milhidaka** [comment]
I fixed the error in master branch.
Please use latest build.
https://github.com/mil-tokyo/webdnn/blob/master/dist/webdnn.js

**Comment by jeffsaremi** [comment]
Thanks very much. it works now on my end too.
